"""Exported loadout — generated by the in-game editor (press S).

Drop-in build_loadout (+ build_gates): relaunch or press F5 to load it.
"""
from __future__ import annotations

from chokepoint.arsenal import MODULE_LIBRARY, Turret, make_gun
from chokepoint.gates import Gate


def build_loadout(unlocked, slots):
    turrets = []
    g0 = make_gun("sieve")
    turrets.append(Turret(340, 120, gun=g0))
    g1 = make_gun("scatter")
    turrets.append(Turret(340, 340, gun=g1))
    return turrets


def build_gates(unlocked, slots):
    return [
    ]
